### ISSUE TITLE
Unable to create folder with same name

### ISSUE THREAD

**Issue by Kimbaras** [jonashellmann/everydocs-core#31]
Hi there,

The title may be a bit misleading, let me explain better that:

So, I'm basically trying to create a folder structure similar to 

```
Root
   Bills
      Energy
         ProviderA
         ProviderB
      Gas
         ProviderA
         ProviderB
```

The issue is that when I try to create "ProviderA" folder under "Gas" folder nothing happens. I believe it may a check if the name / folder already exists in order to avoid duplicates, but no errors or warnings are displayed on the GUI.

If this is the intended behavior, I'd expect a warning about the folder name already existing or something similar.
If it's not intended, then there's an issue :D 

Currently using:
`
everydocs:latest
everydocs-web:latests
mariadb:10.7.3
`

Thanks!

![folder_structure](https://github.com/jonashellmann/everydocs-core/assets/102742484/a3882060-3875-4dbb-a9be-b0c3593b0d5e)
![nothing_happens](https://github.com/jonashellmann/everydocs-core/assets/102742484/15e802d0-0b87-4838-9f2a-61c5f0da7caf)

**Comment by jonashellmann** [comment]
Thank you for opening the issue, this definitely should be fixed! I should be able to investigate this problem in the next days 😄

**Comment by jonashellmann** [comment]
I merge #34 and created a new version 1.4.8. The `everydocs-core:latest` is updated as well.
It should now be possible to have folders but the same name but different parent folders.
